### ISSUE TITLE
Dispatcher Syntax Error

### ISSUE THREAD

**Issue by RavenJSnow** [ajzett/Gilbo-API#20]
Traceback (most recent call last):
  File "C:\Users\Clara\Documents\Gilbo-API-master\Gilbo-API-master\Gilbo-API.py", line 15, in <module>
    from dispatch import Signal, receiver
  File "C:\Users\Clara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\dispatch\__init__.py", line 9, in <module>
    from dispatch.dispatcher import Signal
  File "C:\Users\Clara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\dispatch\dispatcher.py", line 198
    except Exception, err:
                    ^
SyntaxError: invalid syntax

There seems to be an error in the dispatch module itself. It is possible the module isn't installed correctly if it works on other computers.

**Comment by RavenJSnow** [comment]
Error in installation, using the wrong dispatcher.
